language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install nose2 pylint
  - pip install .

# command to run tests
script:
  - nose2 -s data
  - pytest ./tests/unit
#  - find . -name "*.py" -exec pylint -E --disable=import-error '{}' +
branches:
  only:
  - master
  - development
  - dev
